stages:
    - build_ui
    - build_jar
    - deploy
    
build_ui:
    stage: build_ui
    image: node:latest
    script:
        - cd chameleon-client
        - npm install
        - npm run build
    artifacts:
        paths:
            - chameleon-client/dist
        
build_jar:
    stage: build_jar
    image: maven:3.6.2-jdk-12
    script:
        - rm -r Main/src/main/resources/web/*
        - mv chameleon-client/dist/* Main/src/main/resources/web
        - cd Main 
        - mvn package
    artifacts:
        paths:
        - Main/target
deploy:
    stage: deploy
    image: monachus/hugo:latest
    before_script:
        - apt-get update
        - apt-get --yes --force-yes install git ssh rsync
        - git submodule update --init --recursive
    script:
        - echo "${SSH_PRIVATE_KEY}" > id_rsa
        - chmod 700 id_rsa
        - mkdir "${HOME}/.ssh"
        - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
        - cd Main
        - rsync -e 'ssh -i id_rsa' target/* oriagranat9@frs.sourceforge.net:/home/frs/project/ori-test/
