stages:
    - build_ui
    - build_jar
    
build_ui:
    stage: build_ui
    image: node:latest
    script:
        - cd chameleon-client
        - npm install
        - npm run build
    artifacts:
        paths:
            - dist/
        
build_jar:
    stage: build_jar
    image: maven:3.6.2-jdk-12
    script:
        - mv chameleon-client/dist/* Main/src/main/resources/web
        - cd Main 
        - mvn package