stages:
    - build_ui
    - build_jar
    
build_ui:
    stage: build_ui
    image: node:latest
    script:
        - cd chameleon-client
        - npm install
        - npm run build
    artifacts:
        paths:
            - chameleon-client/dist
        
build_jar:
    stage: build_jar
    image: maven:3.6.2-jdk-12
    before_script:
    - apk update && apk add openssh-client bash rsync
    script:
        - rm -r Main/src/main/resources/web/*
        - mv chameleon-client/dist/* Main/src/main/resources/web
        - cd Main 
        - mvn package
        - eval $(ssh-agent -s)
        - bash -c 'ssh-add <(echo "${SSH_PRIVATE_KEY}")'
        - mkdir -p ~/.ssh
        - echo "${SSH_HOST_KEY}" > ~/.ssh/known_hosts
        - rsync -e ssh ./target/chameleon-vision-$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) ${SSH_USER}@frs.sourceforge.net:/home/frs/project/ori-test/