version: 2
jobs:
  build_ui:
    working_directory: ~/project/chameleon-client
    docker:
      - image: node:latest

    steps:
      - checkout:
          path: ~/project
      
      - run: npm install
      - run: npm run build
      
      # - store_artifacts: 
      #     path: dist/
      - persist_to_workspace:
          root: chameleon-client
          paths:
            - dist

  
  build_jar:
    working_directory: ~/project/Main
    docker:
      - image: maven:3.6.2-jdk-12
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: /project/chameleon-client
        
      - run: rm -r src/main/resources/web/*
      - run: ../chameleon-client/dist/* Main/src/main/resources/web
      - run: mvn package
      - store_artifacts: 
          path: target/

workflows:
  version: 2
  release:
    jobs:
      - build_ui
      - build_jar:
          requires:
            - build_ui