version: 2
jobs:
  build_ui:
    docker:
      - image: node:latest

    steps:

      - checkout
      
      - run: cd chameleon-client
      - run: npm install
      - run: npm run build
      
      - store_artifacts: 
          path: chameleon-client/dist/*

workflows:
  version: 2
  release:
    jobs:
      - build_ui