version: 2
jobs:
  build_ui:
    working_directory: ~/project/chameleon-client
    docker:
      - image: node:latest

    steps:

      - checkout:
          path: ~/project
      
      - run: cd chameleon-client
      - run: npm install
      - run: npm run build
      
      - store_artifacts: 
          path: dist/

workflows:
  version: 2
  release:
    jobs:
      - build_ui